LSYbuilds/campingsmore

src/css/community-style.js, src/css/community-write-style.js, src/pages/Community.js, src/pages/CommunityWrite.js
=> feat: 커뮤니티 섹션 작업중

src/css/payment-style.js, src/pages/Payment.js
=> feat: 결제페이지 작업중

src/css/main-contents-style.js, src/pages/MainContents.js
=> feat: 색상 디자인변경 작업중

src/css/community-bulletin-board-style.js, src/css/community-style.js, src/css/community-write-style.js, src/css/review-modal-style.js, src/pages/Community.js, src/pages/CommunityBulletinBoard.js, src/pages/CommunityWrite.js
=> feat: review modal 작업 및 커뮤니티 게시글 작성중

src/api/communityFetch.js, src/css/community-bulletin-board-style.js, src/pages/Community.js, src/pages/CommunityBulletinBoard.js
=> feat: community 페이지 기능 구현 중

src/api/communityFetch.js, src/css/community-bulletin-board-style.js, src/css/community-write-style.js, src/pages/Community.js, src/pages/CommunityBulletinBoard.js
=> feat: community 작업

src/api/basketFetch.js, src/css/payment-style.js, src/pages/Basket.js, src/pages/Payment.js
=> feat: basket 페이지 작업중

src/css/login-style.js, src/css/orderlist-style.js, src/pages/OrderDetail.js, src/pages/OrderList.js
=> feat: orderlist 최신랭킹

src/api/communityBulletinBoardFetch.js, src/api/communityFetch.js, src/pages/Basket.js, src/pages/Community.js, src/pages/CommunityBulletinBoard.js
=> feat: communityBulletinBoard 페이지 작업중

src/api/communityBulletinBoardFetch.js, src/reducers/basketSlice.js, src/store/store2.js
=> feat: basket 페이지 redux-toolkit 적용

package.json, src/api/communityBulletinBoardFetch.js, src/api/communityFetch.js, src/api/paymentFetch.js, src/css/review-modal-style.js, src/pages/Community.js, src/pages/CommunityBulletinBoard.js, src/pages/Payment.js, yarn.lock
=> feat: payment 페이지 작업

src/api/basketFetch.js, src/api/itemFatch.js, src/components/BasketModal.js, src/components/Header.js, src/css/orderdetail-style.js, src/pages/OrderDetail.js, src/pages/OrderList.js
=> feat: 장바구니 담기 기능 완료

src/api/basketFetch.js, src/pages/Basket.js
=> feat: basket 페이지 delete 작업중

src/pages/OrderDetail.js
=> feat : 이거 올라가냐?

src/pages/OrderDetail.js, src/pages/OrderList.js
=> feat : OrderDetail 수정

src/components/PaymentModal.js, src/pages/OrderList.js
=> feat: 게시글 작성 페이지 작업중

package.json, src/api/communityBulletinBoardFetch.js, src/api/communityWriteFetch.js, src/css/community-bulletin-board-style.js, src/pages/Community.js, src/pages/CommunityBulletinBoard.js, src/pages/CommunityWrite.js, yarn.lock
=> feat: 게시글 디테일, 게시글 작성 페이지 작업중

src/api/DaumPost.js, src/api/paymentFetch.js, src/css/basket-style.js, src/css/orderdetail-style.js, src/css/orderlist-style.js, src/css/payment-style.js, src/pages/Account.js, src/pages/OrderDetail.js, src/pages/Payment.js, src/reducers/orderItemSlice.js, src/store/store2.js
=> feat: 디자인 디테일 작업중

src/css/orderdetail-style.js, src/css/payment-style.js, src/pages/Basket.js, src/pages/OrderDetail.js, src/pages/OrderList.js, src/pages/Payment.js
=> feat: orderdetail 디자인 디테일 작업

src/components/CommentList.js, src/css/comment-list-style.js, src/css/community-bulletin-board-style.js, src/css/community-style.js, src/css/community-write-style.js, src/pages/CommunityBulletinBoard.js, src/pages/CommunityWrite.js
=> feat:작성글 CSS 수정

src/components/CommentList.js, src/components/modal/CommentDeleteModal.js, src/css/comment-list-style.js, src/css/community-bulletin-board-style.js, src/css/modalStyle/comment-delete-style.js, src/pages/CommunityBulletinBoard.js
=> feat: commentList 페이지 작업완료
